### ISSUE TITLE
Order of errors not in document order

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-gramcheck-web#1]
For the following text:

> – Mun háliidan doarjut Bonju Sápmelaččaid ja illudin searvat ráidovázzimii singuin lávvardaga, cealká gielda- ja ođasmahttinministtar Jan Tore Sanner,gii ovddasvástida ovddasvástida sámi áššiid ráđđehusas.Europride-festivála loahpahuvvui ráidovázzimiin Oslo gáhtain mannan lávvardaga?Bonju Sápmelaččat vázze sierra joavkun dán ráidovázzimis!Lassin dasa lei vel Queering Sápmi-čájálmas Pride Parkas Ráđđeviesu šiljus. 

the grammar checker reports three errors:

* Bonju
* Sanner,gii
* lávvardaga

in that order. But in the text, the order is actually:

* Bonju
* lávvardaga
* Sanner,gii

Not a major issue, but surprising to the user.

This is true for both MSWord and GoogleDocs, so appears to be a thing on the server.

**Comment by bbqsrc** [comment]
More likely to be UI or libdivvun, as nothing changes the order on the server as far as I can see.

**Comment by snomos** [comment]
It is the UI. There are two lávvardaga in the text, and the first is before the `,gii`case, and is highlighted. But that is not the one with the error. `libdivvun` reports the offset of the error correctly as far as I can see, so the error must then be in the UI. Here is the output from libdivvun:

```json
$ echo '– Mun háliidan doarjut Bonju Sápmelaččaid ja illudin searvat ráidovázzimii singuin lávvardaga, cealká gielda- ja ođasmahttinministtar Jan Tore Sanner,gii ovddasvástida ovddasvástida sámi áššiid ráđđehusas.Europride-festivála loahpahuvvui ráidovázzimiin Oslo gáhtain mannan lávvardaga?Bonju Sápmelaččat vázze sierra joavkun dán ráidovázzimis!Lassin dasa lei vel Queering Sápmi-čájálmas Pride Parkas Ráđđeviesu šiljus.' | divvun-checker -a tools/grammarcheckers/se.zcheck | jq .
{
  "errs": [
    [
      "Bonju",
      23,
      28,
      "typo",
      "Ii leat sátnelisttus",
      [],
      "Čállinmeattáhusat"
    ],
    [
      ",gii",
      149,
      153,
      "no-space-after-punct-mark",
      "Ii leat gaska \",\" maŋis",
      [
        ", gii"
      ],
      "Sátnegaskameattáhusat"
    ],
    [
      "lávvardaga",
      273,
      283,
      "typo",
      "Ii leat sátnelisttus",
      [],
      "Čállinmeattáhusat"
    ]
  ],
  "text": "– Mun háliidan doarjut Bonju Sápmelaččaid ja illudin searvat ráidovázzimii singuin lávvardaga, cealká gielda- ja ođasmahttinministtar Jan Tore Sanner,gii ovddasvástida ovddasvástida sámi áššiid ráđđehusas.Europride-festivála loahpahuvvui ráidovázzimiin Oslo gáhtain mannan lávvardaga?Bonju Sápmelaččat vázze sierra joavkun dán ráidovázzimis!Lassin dasa lei vel Queering Sápmi-čájálmas Pride Parkas Ráđđeviesu šiljus."
}
```

**Comment by snomos** [comment]
I am not able to reproduce this anymore, consider it fixed.
