### ISSUE TITLE
GramDivvun does not work in Word 2016 on Mac

### ISSUE THREAD

**Issue by biret365** [divvun/divvun-gramcheck-web#11]
I have installed GramDivvun on Mac but it does not work and I do not get any suggestions when running the grammer checker. I have Word 2016.
![gramcheck](https://user-images.githubusercontent.com/62298166/76872055-2da89100-686c-11ea-9c99-345e7d81f1d9.png)
![šord](https://user-images.githubusercontent.com/62298166/76872167-5761b800-686c-11ea-8a54-678fd28c2fc7.png)

**Comment by biret365** [comment]
This problem is solved. It was a user created problem. Under settings, I had unfortunately selected to ignore all error types, see attached photo. 
I unselected them all and GramDivvun works on my Mac now. :-) 
![error](https://user-images.githubusercontent.com/62298166/76954054-03a8aa80-6910-11ea-8eb9-a9dbe398f8f5.png)

**Comment by bbqsrc** [comment]
Hey @biret365, thanks for the debugging!

We should add some kind of notice for the user when checking doesn't do anything because all error types are ignored. Glad you got it sorted!
