### ISSUE TITLE
Make grammar checker settings easier to use

### ISSUE THREAD

**Issue by bbqsrc** [divvun/divvun-gramcheck-web#12]
User expectations for how the grammar settings page behaves are inverse to what is happening right now.

Users expect checking the boxes to enable the grammar rules, not disable them. Invert this, and the text accompanying the settings screen to make it clearer what the behaviour is.

**Comment by zoomix** [comment]
![image](https://github.com/divvun/divvun-gramcheck-web/assets/813082/4c36d613-67b9-4620-85c7-76fc505854f3)

![image](https://github.com/divvun/divvun-gramcheck-web/assets/813082/13bbc6b0-b4c6-4d20-bacd-701c51452e91)

Solution

**Comment by snomos** [comment]
Works in both GDocs and Word. Closed.
