### ISSUE TITLE
JS errors and missing settings, CSS

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-gramcheck-web#22]
Environment:

- MS Office 365, private account
- GramDivvun from the O365 plugin store (ie not UiT)
- Chrome browser
- macOS

CSS styling is missing (see screenshots), and part of the functionality is also missing (List, Settings buttons are plain text). The grammar checker works otherwise.

![Bilde 15 09 2020 klokken 09 52](https://user-images.githubusercontent.com/1255285/93176315-c47dd980-f739-11ea-8ca0-027862e61729.jpg)
![Bilde 15 09 2020 klokken 09 53](https://user-images.githubusercontent.com/1255285/93176322-c5af0680-f739-11ea-9d69-0705d3c98d2b.jpg)

In the Devtools console, there are a number of errors and failures:

```js
DevTools failed to load SourceMap: Could not load content for https://c1-word-edit-15.cdn.office.net/we/s/161331041000_App_Scripts/otelFull.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

```
word.boot.js:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://word-edit.officeapps.live.com/we/RemoteUls.ashx?usid=c4147c3a-63a8-4f06-91c8-868858b8f29a with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

and many more.

**Comment by fry** [comment]
Fixed and deployed, styling looks fine again from my side. Confirm and close please @snomos :)

**Comment by snomos** [comment]
Looks great, and works great!
