### ISSUE TITLE
No feedback during checking, seems frozen

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-gramcheck-web#49]
After pressing "Check grammar", the GDocs extension stares back at you, empty in sight, and a bit washed out. It seems very dead. For short docs this is not a major issue, as there is a response returned pretty fast. But for long docs this will lead the user to believe that nothing is happening, and that the checker has stopped working. In the MS Word extention, there is a nice little feedback ring rotating while checking is going on, so that the user is confident that something is actually happening.

Screen shot of dead eyes:
<img width="413" alt="Skjermbilde 2022-01-26 kl  08 40 50" src="https://user-images.githubusercontent.com/1255285/151120556-6403de0c-a66e-45cd-abd2-b76ad5a650ca.png">

As comparison, screen shot of less dead eyes in Word:
<img width="433" alt="Skjermbilde 2022-01-26 kl  08 34 59" src="https://user-images.githubusercontent.com/1255285/151120709-2b01cbf8-bfce-44ac-b6c5-b5ebf9b9d653.png">

**Comment by bbqsrc** [comment]
From your own screenshot, at the bottom:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/279099/151121441-07173cfc-b65c-4c04-851e-7a04978f7e14.png">

**Comment by snomos** [comment]
Seems to work as intended. Closing.
