### ISSUE TITLE
The missing grc easteregg

### ISSUE THREAD

**Issue by Trondtr** [divvun/divvun-gramcheck-web#67]
There is no easteregg of the "nuvviDspeller" type for our grammarcheckers. One might think they are not needed, since the use normally accesses the server, and whatever version problems present should be shared by server and user machines alike. But upon debugging the smn grc for the sentence

- *Mij eelijm tagarijn puáris kaavpugijn.*

we run into the following problem: The sentence is correct, and flagged as such (= no error flag) on my command line, my MS Word, my Google Doc. For my collegue, the Google Doc version behaves as expected, whereas the MS Word version gives a false positive. 

An obvious debugging tool would thus be an easteregg.

**Comment by snomos** [comment]
Moved and closed, it fits better at [the new place](https://github.com/giellalt/giella-core/issues/23).
