### ISSUE TITLE
Scrolling area too large in MS Office 365 for mac

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-gramcheck-web#7]
The top boundary of the scrolling area for the error + suggestion list is too high, so that when scrolling the errors and suggestions upwards, the text and buttons overlap with the language seleection and check button:

![gramcheck_error](https://user-images.githubusercontent.com/1255285/73885848-c78e1e80-4868-11ea-9b99-ed73ebb80e7a.png)

Tested on a new installation of MS Office 365 for macOS.

**Comment by snomos** [comment]
Ignore the dollar errors, we are looking into those 🙂

**Comment by fry** [comment]
This appeared to be an issue with Safari, https://github.com/divvun/divvun-gramcheck-web/commit/c446474adaa31b7ef5eceb11ea8761c8e7027505 should fix this.
