### ISSUE TITLE
Office 365 extension is still having issues with mid-word and multiple hits

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-gramcheck-web#89]
Cf:

![image](https://github.com/divvun/divvun-gramcheck-web/assets/1255285/9a9b4b4e-d21c-42d2-86a2-67a5975d7410)

Text for reproducing the error:

> Åhpadidjestudenta oadtju aj máhtudagav ja bessi oahpástuvvat terminologijjajn, barggovuogij ja sosiolingvistihkalasj dilijn. Åhpadiddjestudenta ma ælla dáj tiemáj barggam soajttá rahtji ienebut gå barggagåhti. Mánájgárden ja skåvlån hæhttuji ham guovte láhkáj barggat jus guovte mánnájuohkusijs galggi sjaddat produktijva sámegielak máná. Ij le diedon åhpadiddjijda álkke gut vierttiji åhpadit oahppijt gænna le sámegiella iednegiellan ja ådåálggijt aktan. Dákkir barggodille la gássjelis åhpadiddjáj. Danen le sluogas juohket mánájt guokta juohkusijda. Gå máná skåvllåj båhti de galggi máná aj oahppat låhkåt daj guokta gielajda. Máná gejn li gájkbelak åtsådalllama árkkabiejves ja buorre báhkodádjadibme, oahppi buorebut ja jåhtelappot ienni gå máná gænna li binnep åtsådallama ja binnep báhkoboanndudahka. Danen la ájnas jut oahppe oahpástuvvi ådå bágojda ja moallánagájda ma moattelágásj tebmáj gulluji, dát nanni låhkåmåhpadusáv. Máhttep javllat nav garrasit, mánáj åtsådallama li iesj vuodo gå galggi oahppat. Åhpadiddje gudi lij diedulattjat barggam báhkuboanndudagájn, li åtsådallam oahppe le ålov oahppam.
> Sámedikkepresidænnta la ávon gå dal vuododuvvá almmulasj nammadus gut galggá guoradallat dåjmajt ja årnigijt sámegielåhpadus hárráj. Moatten sajen oahppe e oattjo dav fáládagáv majt galggi. Ij le skåvlå ietjas duogen jus sáme åhpadusáv fálli ietjas oahppijda. Skåvllåæjgádin gænna ij la åhpadiddje mij máhttá sámev åhpadit, hættu de ietjas oahppijda sáme åhpadimev alternatijvva åhpadimvuogij baktu vaddet. Oahppijn gænna ælla sámegielak åhpadiddje tjanadum bájkálasj skåvllåj, máhtti oadtjot guhkásåhpadimev duolloj dálloj videorustigij tjadá. -Lip oajvvadam dåjmajt ja láhkarievddadusájt dán nammadussaj, nannitjit dilev oahppijda gænna li sámegiella fáhkan. Buorre åhpadusáv sáme mánnájda fállat la læhkám roaŋkok bálges, ja ep la ájn vuorbástuvvam, valla Sámedigge i vuollána dájna bargujn.
> Åhpadiddje iesj låggŋiji hásstalusájt oahpponævoj hárráj. -Åvddåla mij åhpadiddje viehkedima nubbe nuppev ja mij iesj hábbmima oahpponævojt. Buorep barggovuohke ij gávnnum gå vájllujma oahpponævojt. Valla uddni li åhpadiddjijn nav ållo dåjma, ep desti asta oahpponævoj barggat. Danen de vierttij dát dille buoreduvvat.

Language: Julevsámi / Lule Sámi

This happens with the present code on the production server. Ensured by emptying the cache and reloading the extension from the server.

**Comment by snomos** [comment]
Just to confirm: this is still an issue.

**Comment by zoomix** [comment]
Deployed as of 2024-04-25 13:00 UTC
