### ISSUE TITLE
MSWord extension showing whole document as context

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-gramcheck-web#90]
Cf the test text in #89. For some of the errors (but not all), the whole document is shown as context, with paragraph shifts as unknown boxes (marked with red circles):

![image](https://github.com/divvun/divvun-gramcheck-web/assets/1255285/22d95cd3-7de6-4192-9b50-4d40f3188d58)

The bug seems to go along with #89.

**Comment by zoomix** [comment]
Deployed as of 2024-04-25 13:00 UTC
